kind: pipeline
name: default

steps:
- name: Install Meteor
  image: ubuntu
  commands:
    - echo "install meteor"
  when:
    branch:
      include:
      - develop
    event:
      include:
      - push
      - tag
      exclude:
      - pull_request

trigger:
  branch:
    exclude:
    - master
